---
abstract: 'Intercept all emails and redirect them to a specific address'
author:
  - 'Stefan Hornburg (Racke) <racke@linuxia.de>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Email-Sender-Transport-Redirect
no_index:
  directory:
    - t
    - inc
requires:
  Email::Sender: 0
  Moose: 0
  Test::More: 0
resources:
  repository: https://github.com/racke/Email-Sender-Transport-Redirect
version: 0.0001
